#auto mapping routes
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#manual mapping routes
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: organization-service
#          uri: lb://organization-service
#          predicates:
#            - Path=/organization-service/**
#          filters:
#            - RewritePath=/organization-service/(?<path>.*), /$\{path}
#        - id: licensing-service
#          uri: lb://licensing-service
#          predicates:
#            - Path=/licensing-service/**
#          filters:
#            - RewritePath=/licensing-service/(?<path>.*), /$\{path}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8030/eureka/

server:
  port: 8050

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true