spring:
  datasource:
    url: jdbc:postgresql://database:5432/ostock_dev
    username: postgres
    password: postgres

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8030/eureka/

server:
  port: 8020

logging:
  level:
    org.ilia: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"