spring:
  datasource:
    url: jdbc:postgresql://database:5432/ostock_dev
    username: postgres
    password: postgres

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8030/eureka/

server:
  port: 8040

management:
  endpoints:
    web:
      exposure:
        include: "*"