spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://keycloak:8080/realms/spmia-realm/protocol/openid-connect/token/introspect
          client-id: ostock
          client-secret: o7b9NXfdIsgvcIMgK1MTAZ8gNoLLGHZl

keycloak:
  server-url: http://keycloak:8080
  realm: spmia-realm
  email: ilia@gmail.com
  password: ilia
  client-id: ostock
  client-secret: o7b9NXfdIsgvcIMgK1MTAZ8gNoLLGHZl
  grant_type: password

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8030/eureka/

server:
  port: 8060

management:
  endpoints:
    web:
      exposure:
        include: "*"